#!/bin/bash

# Vercel Environment Variables Setup Script
# This script provides the commands to set environment variables in Vercel
# Run these commands after deploying your projects

echo "============================================"
echo "Vercel Environment Variables Setup"
echo "============================================"
echo ""
echo "⚠️  IMPORTANT: This script shows you what to set."
echo "You need to manually add these in Vercel Dashboard or use Vercel CLI"
echo ""
echo "============================================"
echo "FRONTEND PROJECT (your-frontend-domain.vercel.app)"
echo "============================================"
echo ""
echo "Run these commands (replace PROJECT_NAME with your frontend project name):"
echo ""
echo "vercel env add VITE_API_URL production"
echo "# Enter: https://your-backend-domain.vercel.app"
echo ""
echo "vercel env add VITE_SUPABASE_URL production"
echo "# Enter: https://your-project-id.supabase.co"
echo ""
echo "vercel env add VITE_SUPABASE_ANON_KEY production"
echo "# Enter: YOUR_SUPABASE_ANON_KEY_FROM_DASHBOARD"
echo ""
echo ""
echo "============================================"
echo "BACKEND PROJECT (your-backend-domain.vercel.app)"
echo "============================================"
echo ""
echo "Run these commands (replace PROJECT_NAME with your backend project name):"
echo ""
echo "vercel env add NODE_ENV production"
echo "# Enter: production"
echo ""
echo "vercel env add FRONTEND_URL production"
echo "# Enter: https://your-frontend-domain.vercel.app"
echo ""
echo "vercel env add PORT production"
echo "# Enter: 3001"
echo ""
echo "vercel env add PLATFORM_WALLET_PRIVATE_KEY production"
echo "# Enter: YOUR_PLATFORM_WALLET_PRIVATE_KEY"
echo "# ⚠️  Generate a new Solana wallet keypair and export as JSON array"
echo "# Format: [42,5,181,154,...] or comma-separated: 42,5,181,154,..."
echo ""
echo "vercel env add SUPABASE_URL production"
echo "# Enter: https://your-project-id.supabase.co"
echo ""
echo "vercel env add SUPABASE_SERVICE_KEY production"
echo "# Enter: YOUR_SERVICE_KEY_FROM_SUPABASE_DASHBOARD"
echo ""
echo "vercel env add SUPABASE_ANON_KEY production"
echo "# Enter: YOUR_SUPABASE_ANON_KEY_FROM_DASHBOARD"
echo ""
echo ""
echo "============================================"
echo "NEXT STEPS:"
echo "============================================"
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Login: vercel login"
echo "3. Link project: vercel link (in project directory)"
echo "4. Run the commands above for each project"
echo "5. Or set them manually in Vercel Dashboard"
echo ""
echo "See VERCEL_SETUP.md for detailed instructions"
echo ""
