#!/bin/bash

# Vercel Environment Variables Setup Script
# This script provides the commands to set environment variables in Vercel
# Run these commands after deploying your projects

echo "============================================"
echo "Vercel Environment Variables Setup"
echo "============================================"
echo ""
echo "⚠️  IMPORTANT: This script shows you what to set."
echo "You need to manually add these in Vercel Dashboard or use Vercel CLI"
echo ""
echo "============================================"
echo "FRONTEND PROJECT (lancerfi.app)"
echo "============================================"
echo ""
echo "Run these commands (replace PROJECT_NAME with your frontend project name):"
echo ""
echo "vercel env add VITE_API_URL production"
echo "# Enter: https://lancerfi-backend.vercel.app"
echo ""
echo "vercel env add VITE_SUPABASE_URL production"
echo "# Enter: https://xhxcfyosctbvlvewyptf.supabase.co"
echo ""
echo "vercel env add VITE_SUPABASE_ANON_KEY production"
echo "# Enter: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeGNmeW9zY3Ridmx2ZXd5cHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Nzg1OTYsImV4cCI6MjA3MzQ1NDU5Nn0.8q6W5IUDAq5-pSl16kiqD3hh21dymAlm9TeYZiv7EqA"
echo ""
echo ""
echo "============================================"
echo "BACKEND PROJECT (lancerfi-backend)"
echo "============================================"
echo ""
echo "Run these commands (replace PROJECT_NAME with your backend project name):"
echo ""
echo "vercel env add NODE_ENV production"
echo "# Enter: production"
echo ""
echo "vercel env add FRONTEND_URL production"
echo "# Enter: https://lancerfi.app"
echo ""
echo "vercel env add PORT production"
echo "# Enter: 3001"
echo ""
echo "vercel env add PLATFORM_WALLET_PRIVATE_KEY production"
echo "# Enter: [42,5,181,154,222,194,111,64,16,174,210,187,67,57,170,221,248,66,193,128,206,99,175,43,227,148,151,241,103,222,95,247,142,136,13,111,101,232,21,192,245,212,73,63,83,128,143,19,163,2,148,5,180,208,163,2,250,19,54,176,242,158,13,3]"
echo ""
echo "vercel env add SUPABASE_URL production"
echo "# Enter: https://xhxcfyosctbvlvewyptf.supabase.co"
echo ""
echo "vercel env add SUPABASE_SERVICE_KEY production"
echo "# Enter: YOUR_SERVICE_KEY_FROM_SUPABASE_DASHBOARD"
echo ""
echo "vercel env add SUPABASE_ANON_KEY production"
echo "# Enter: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeGNmeW9zY3Ridmx2ZXd5cHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Nzg1OTYsImV4cCI6MjA3MzQ1NDU5Nn0.8q6W5IUDAq5-pSl16kiqD3hh21dymAlm9TeYZiv7EqA"
echo ""
echo ""
echo "============================================"
echo "NEXT STEPS:"
echo "============================================"
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Login: vercel login"
echo "3. Link project: vercel link (in project directory)"
echo "4. Run the commands above for each project"
echo "5. Or set them manually in Vercel Dashboard"
echo ""
echo "See VERCEL_SETUP.md for detailed instructions"
echo ""

